sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"

cache:
    apt: true
    pip: true
    directories:
        - $HOME/download-cache
        - $HOME/.cache/pre-commit

env:
    - SOLRCLOUD=false
    - SOLRCLOUD=true

matrix:
    allow_failures:
        - python: "pypy"

addons:
    apt_packages:
        - default-jdk

install:
    - "pip install 'requests>2' coverage codecov pre-commit"
    - "pip install ."
    - 'if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then travis_retry pip install faulthandler; fi'
    - 'if [[ "${SOLRCLOUD:-false}" == "true" ]]; then pip install -e .[solrcloud]; fi'

script:
    - coverage run run-tests.py
    - git fetch --unshallow
    - git diff --name-only $TRAVIS_COMMIT_RANGE | xargs pre-commit run --files

after_success:
    - codecov

notifications:
    email: false
